Allow default values and disallow overriden env vars

diff --git a/hooks/environment b/hooks/environment
--- a/hooks/environment
+++ b/hooks/environment
@@ -40,21 +40,24 @@ function read_meta_data() {
   local meta_data_key_alias
   local mapped_key
 
-  IFS='=' read -ra key_mapped <<< "$key_item"
+  IFS='=;' read -ra key_mapped <<< "$key_item"
 
   meta_data_key=${key_mapped[0]:-}
   meta_data_key_alias=${key_mapped[1]:-}
   mapped_key=${meta_data_key_alias:-$meta_data_key}
+  default_val=${key_mapped[2]:-}
 
-  value=$(buildkite-agent meta-data get "$meta_data_key")
+  eval "env=\"\${$mapped_key+x}\""
+  if [[ -n "$env" ]]; then return; fi
 
-  if [[ -n "$value" ]]; then
-    echo "${mapped_key}=(${#value} chars)" >&2;
-    echo "${mapped_key}=${value}"
-  else
-    echo "Could not read meta-data: ${meta_data_key}" >&2;
+  value=$(buildkite-agent meta-data get "$meta_data_key" --default "$default_val")
+  if [[ -z "$value" && "$key_mapped" != *\;* ]]; then 
+    echo "Could not read meta-data: ${meta_data_key} and no default value supplied" >&2;
     exit 1
   fi
+
+  echo "${mapped_key}=(${#value} chars)" >&2;
+  echo "${mapped_key}=\"${value}\""
 }
 
 main
